name: Build Docker Push
author: "Julien Anquetil"
description: "A Github Action that build the docker image of the application and push it to AWS ECR."

inputs:
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  AWS_REGION:
    required: false
    default: 'eu-west-3'
  AWS_ECR_REPO:
    required: true
  PLATFORM:
    required: false
    default: "linux/amd64"
  TAGNAME:
    required: false
    default: ${GITHUB_REF##*/}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.TAGNAME }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set branch name as env variable
      run: |
        currentbranch=$(echo ${GITHUB_REF##*/})
        echo "running on $currentbranch"
        echo "BRANCH=$currentbranch" >> $GITHUB_ENV
      shell: bash

    - name: Setup AWS ECR Details
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{inputs.AWS_REGION}}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
         context: .
         push: true
         platforms: ${{inputs.PLATFORM}}
         tags: ${{ steps.login-ecr.outputs.registry }}/${{inputs.AWS_ECR_REPO}}:${{ inputs.TAGNAME }}
         cache-from: type=gha
         cache-to: type=gha,mode=max
         provenance: false
         build-args: |
            NEWRELIC_APPNAME
