name: Build Docker Push
on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  Build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
