name: "Coding Standard"
author: "Graycore"
description: "A Github Action that runs the Magento Coding Standard."

inputs:
  php_version:
    required: true
    default: "8.3"
    description: "PHP version used to do the coding standard check."

  composer_version:
    required: true
    default: "2"
    description: "The version of composer to use."

  path:
    required: true
    default: 'app/code'
    description: "The directory (relative to the project root) in which the coding standard will be checked. Used when the event is not a pull request."

  version:
    required: false
    default: "37"
    description: "The version of the coding standard to use. If not provided, will use the latest version."
  
  extensions:
    required: false
    description: "Run PHPCS against specific extensions"

runs:
  using: composite
  steps:
    - name: Checkout Project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: project

    - name: Create Standard Directory
      shell: bash
      run: mkdir standard

    - name: Set PHP Version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        tools: composer:v${{ inputs.composer_version }}, cs2pr
        coverage: none
  
    - name: Enable dealerdirect/phpcodesniffer-composer-installer plugin
      shell: bash
      working-directory: standard
      run: composer config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true --global
      
    - name: Install Coding Standard
      shell: bash
      working-directory: standard
      run: composer require "magento/magento-coding-standard:${{ inputs.version || '*' }}"

    - name: Get Changed Files
      shell: bash
      working-directory: project
      id: changed-files
      run: echo "files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
      if: github.event_name == 'pull_request'

    - name: Coding Standard Check
      shell: bash
      id: phpcs
      continue-on-error: true
      run: |
        ../standard/vendor/bin/phpcs --standard=Magento2 \
        --exclude=Generic.Files.LineLength \
        --ignore=dev/*,docker/*,setup/*,lib/* \
        --report=checkstyle \
        --report-file=phpcs-report.xml \
        -q \
        --extensions=${{ inputs.extensions || '*' }} \
        ${{ github.event_name == 'pull_request' && steps.changed-files.outputs.files || inputs.path }}
      working-directory: project

    - name: Show PHPCS results in PR
      shell: bash
      # Only run if phpcs step didn't skip (e.g., if there's no code to check) and the report file exists
      if: ${{ always() && steps.phpcs.outcome != 'skipped' && hashFiles('project/phpcs-report.xml') != '' }}
      run: cs2pr ./phpcs-report.xml
      working-directory: project # Add working directory here
